// Code in this package is generated by protoc. Run `make proto` to regenerate.
//
//go:generate protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative -I../../proto ../../proto/auth.proto
package pb
